{% set name = "optional-lite" %}
{% set version = "3.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/martinmoene/optional-lite/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2be17fcfc764809612282c3e728cabc42afe703b9dc333cc87c48d882fcfc2c2

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - test -f $PREFIX/include/nonstd/optional.hpp  # [unix]
    - if not exist %LIBRARY_INC%\\nonstd\\optional.hpp exit 1  # [win]

about:
  home: https://github.com/martinmoene/optional-lite
  summary: A C++17-like optional, a nullable object for C++98, C++11 and later in a single-file header-only library
  license: BSL-1.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xhochy
